title: Tejas | Data Science Portfolio
description: Data Science | Python | Artificial Itelligence| Machine Learning 
theme: jekyll-theme-orderedlist

# Site settings
url: https://Tejaskuranjekar.github.io
baseurl: ""

# Author info
author:
  name: Tejas
  email: tejasKuranjekar10@email.com
  github: https://github.com/TejasKuranjekar
  linkedin: https://linkedin.com/in/tejas-kuranjekar-838b47254/

# Build settings
markdown: kramdown
